# Generated by Django 5.0.7 on 2024-08-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_hsncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvariants',
            name='Options',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
