# Generated by Django 5.0.7 on 2024-08-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subvariants_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='Options',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
