# Generated by Django 5.0.7 on 2024-08-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_variants_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subvariants',
            name='Stock',
        ),
    ]
